/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by Documentation/scheduler/sched-pelt; do not modify. */

static const u32 runnable_avg_yN_inv[] __maybe_unused = {
	0xffffffff,0xd744fcc9,0xb504f333,0x9837f050,
};

static const u32 runnable_avg_yN_sum[] = {
	    0,  861, 1585, 2193, 2705, 3135, 3497, 3801, 4057,
};

#define LOAD_AVG_PERIOD 8
#define LOAD_AVG_MAX 6430
